import { Term, TermCategory } from './types';

export const CPP_TERMS: Term[] = [
  {
    id: 'app',
    word: 'App',
    ipa: 'æp',
    ipaUS: 'æp',
    ipaUK: 'æp',
    simplePhonetic: 'Ap',
    category: TermCategory.CONCEPT,
    description: '应用程序 (Application) 的缩写。',
    commonError: 'A-P-P (逐字母读)',
    detailedExplanation: 'App 是 Application 的缩写，应该作为一个单词来读，发音类似 "Apple" 的第一个音节。在中文语境中，经常被误读为三个字母 A-P-P，这在英语母语者听起来会非常奇怪。',
    codeSnippet: '// Launching the App\nApplication::Run();'
  },
  {
    id: 'daemon',
    word: 'daemon',
    ipa: 'ˈdiːmən',
    ipaUS: 'ˈdiːmən',
    ipaUK: 'ˈdiːmən',
    simplePhonetic: 'Dee-mon',
    category: TermCategory.CONCEPT,
    description: '守护进程。后台运行的计算机程序。',
    commonError: 'Da-ming (大明) / Day-mon',
    detailedExplanation: '源自希腊语 daimon。在计算机术语中，它指的是在后台运行的服务进程。发音同 "Demon" (恶魔)。很多人受 ae 拼写影响误读为 "Day-mon"。',
    codeSnippet: 'systemd_daemon.start();\n// Runs in background'
  },
  {
    id: 'suite',
    word: 'suite',
    ipa: 'swiːt',
    ipaUS: 'swiːt',
    ipaUK: 'swiːt',
    simplePhonetic: 'Sweet',
    category: TermCategory.TOOL,
    description: '套件。如 Test Suite（测试套件）。',
    commonError: 'Suit (西装 - Su-te)',
    detailedExplanation: '意为“一套”、“组”。发音完全同 "Sweet" (甜)。常见的错误是将其读成 "Suit" (西装)。常见于 "Test Suite" 或 "Office Suite"。',
    codeSnippet: 'TestSuite suite;\nsuite.add(testCase1);'
  },
  {
    id: 'lambda',
    word: 'lambda',
    ipa: 'ˈlæmdə',
    ipaUS: 'ˈlæmdə',
    ipaUK: 'ˈlæmdə',
    simplePhonetic: 'Lam-da',
    category: TermCategory.KEYWORD,
    description: 'Lambda 表达式 / 匿名函数。',
    commonError: 'Lang-da (朗达) / Lam-b-da (发出了b音)',
    detailedExplanation: '希腊字母 Λ。关键点在于字母 `b` 是**不发音**的。许多人会错误地把 b 音发出来。在 C++11 中引入，用于定义匿名函数。',
    codeSnippet: 'auto func = [](int x) {\n    return x * x;\n};'
  },
  {
    id: 'null',
    word: 'null',
    ipa: 'nʌl',
    ipaUS: 'nʌl',
    ipaUK: 'nʌl',
    simplePhonetic: 'Nuhl',
    category: TermCategory.KEYWORD,
    description: '空指针常量。',
    commonError: 'Niu (牛) / Nao (闹)',
    detailedExplanation: '表示“无”。发音应该短促，元音类似 "bus" 中的 u。很多国内开发者受方言或直觉影响，容易读成“牛”或“闹”。',
    codeSnippet: 'int* ptr = nullptr;\nif (ptr == NULL) { ... }'
  },
  {
    id: 'main',
    word: 'main',
    ipa: 'meɪn',
    ipaUS: 'meɪn',
    ipaUK: 'meɪn',
    simplePhonetic: 'Meyn',
    category: TermCategory.KEYWORD,
    description: '程序的主入口函数。',
    commonError: 'Man (慢) / Min (民)',
    detailedExplanation: '主要的意思。发音同 "Pain", "Rain"。元音是双元音 /eɪ/。不要读成短音的 "Man" (男人)。',
    codeSnippet: 'int main() {\n    return 0;\n}'
  },
  {
    id: 'void',
    word: 'void',
    ipa: 'vɔɪd',
    ipaUS: 'vɔɪd',
    ipaUK: 'vɔɪd',
    simplePhonetic: 'Voy-d',
    category: TermCategory.KEYWORD,
    description: '空类型。',
    commonError: 'Woid (沃德 - 混淆v/w音)',
    detailedExplanation: '表示空。关键在于 V 的发音，上牙齿要咬住下嘴唇震动。不要发成 W (圆唇) 的音。',
    codeSnippet: 'void doSomething() {\n    // returns nothing\n}'
  },
  {
    id: 'cache',
    word: 'cache',
    ipa: 'kæʃ',
    ipaUS: 'kæʃ',
    ipaUK: 'kæʃ',
    simplePhonetic: 'Kash',
    category: TermCategory.CONCEPT,
    description: '缓存。计算机中用于高速数据存储的层级。',
    commonError: 'Catch (卡其/抓)',
    detailedExplanation: '法语词源。发音完全同现金 "Cash"。绝对不要读成 "Catch" (抓)。这是一个极其高频的错误。',
    codeSnippet: 'CPU_Cache_L1.flush();\n// Not "Catch"'
  },
  {
    id: 'archive',
    word: 'archive',
    ipa: 'ˈɑːrkaɪv',
    ipaUS: 'ˈɑːrkaɪv',
    ipaUK: 'ˈɑːkaɪv',
    simplePhonetic: 'Ar-kaiv',
    category: TermCategory.TOOL,
    description: '归档/档案。常用于库文件 (.a) 或压缩包。',
    commonError: 'A-chiv (阿七五)',
    detailedExplanation: 'ch 发 /k/ 的音，而不是 /tʃ/。重音在第一个音节。常见于静态库文件后缀 .a (archive)。',
    codeSnippet: 'ar rcs libmylib.a obj.o\n// 创建归档文件'
  },
  {
    id: 'deque',
    word: 'std::deque',
    ipa: 'dɛk',
    ipaUS: 'dɛk',
    ipaUK: 'dɛk',
    simplePhonetic: 'Deck',
    category: TermCategory.STL,
    description: '双端队列 (Double-ended queue)。',
    commonError: 'Di-Q (迪-Q)',
    detailedExplanation: '虽然是 Double-ended Queue 的缩写，但发音约定俗成读作 "Deck" (甲板)。不要按照缩写字母读成 De-Que。',
    codeSnippet: 'std::deque<int> d;\nd.push_front(1);'
  },
  {
    id: 'tuple',
    word: 'std::tuple',
    ipa: 'ˈtʌpəl',
    ipaUS: 'ˈtʌpəl',
    ipaUK: 'ˈtjuːpəl',
    simplePhonetic: 'Tuh-pul',
    category: TermCategory.STL,
    description: '元组。固定大小的异构值集合。',
    commonError: 'Too-ple (吐泡)',
    detailedExplanation: '元音发音类似 "Cup"，比较短促。美式发音中 u 发 /ʌ/。英式有时发 /juː/ (Tju-ple)。不要读成长音的 "Too"。',
    codeSnippet: 'std::tuple<int, double> t(1, 2.5);\nauto [i, d] = t;'
  },
  {
    id: 'schema',
    word: 'schema',
    ipa: 'ˈskiːmə',
    ipaUS: 'ˈskiːmə',
    ipaUK: 'ˈskiːmə',
    simplePhonetic: 'Skee-ma',
    category: TermCategory.CONCEPT,
    description: '模式/架构。常见于数据库或XML设计。',
    commonError: 'She-ma (希玛) / Su-ma',
    detailedExplanation: 'Sch 在这里发 /sk/ 的音，类似 "School"。不要读成 "Schema" (希玛)。',
    codeSnippet: 'CREATE SCHEMA my_schema;\n// SQL or XML definition'
  },
  {
    id: 'char',
    word: 'char',
    ipa: 'kɛər',
    ipaUS: 'kɛr',
    ipaUK: 'kɑː',
    simplePhonetic: 'Care',
    category: TermCategory.KEYWORD,
    description: '字符类型。源自 Character。',
    commonError: 'Cha (恰) / Char (查尔)',
    detailedExplanation: '关于 Char 的发音在英语世界也有争议 (Char/Care/Car)，但在 C++ 标准委员会和大多数正式场合，推荐读作 "Care" (Character 的词头)。英式发音中 "Char" (烧焦) /tʃɑː/ 也存在，但作为 C++ 类型推荐 Care。',
    codeSnippet: 'char c = \'A\';\nconst char* str = "Text";'
  },
  {
    id: 'cout',
    word: 'std::cout',
    ipa: 'siː aʊt',
    ipaUS: 'siː aʊt',
    ipaUK: 'siː aʊt',
    simplePhonetic: 'See-Out',
    category: TermCategory.STL,
    description: '标准字符输出流。',
    commonError: 'Kout (考特)',
    detailedExplanation: 'c 代表 character。cout 是 "Character Output" 的缩写。应该连读为 "See-Out"。读成 "Kout" 是非常典型的错误。',
    codeSnippet: 'std::cout << "Hello World";\n// Reads: See-Out'
  },
  {
    id: 'width',
    word: 'width',
    ipa: 'wɪdθ',
    ipaUS: 'wɪdθ',
    ipaUK: 'wɪdθ',
    simplePhonetic: 'With',
    category: TermCategory.CONCEPT,
    description: '宽度。',
    commonError: 'Wai-si (歪死) / Wid-th (重读th)',
    detailedExplanation: 'd 是不发音的，或者非常轻微。主要发音是 wi + th。以咬舌音结尾。不要加元音变成 "歪死"。',
    codeSnippet: 'int width = 100;\nrect.setWidth(width);'
  },
  {
    id: 'height',
    word: 'height',
    ipa: 'haɪt',
    ipaUS: 'haɪt',
    ipaUK: 'haɪt',
    simplePhonetic: 'Hite',
    category: TermCategory.CONCEPT,
    description: '高度。',
    commonError: 'Hate (黑特) / He-ge-te',
    detailedExplanation: 'ei 发 /ai/ 的音 (High)。结尾是 t。完全同 "High" + "t"。不要读成 "Hate" (恨)。',
    codeSnippet: 'int height = 200;\n// Pronounced like "High-t"'
  },
  {
    id: 'image',
    word: 'image',
    ipa: 'ˈɪmɪdʒ',
    ipaUS: 'ˈɪmədʒ',
    ipaUK: 'ˈɪmɪdʒ',
    simplePhonetic: 'Im-ij',
    category: TermCategory.CONCEPT,
    description: '图像。',
    commonError: 'Im-age (意妹支)',
    detailedExplanation: '重音在第一个音节。a 发 /ɪ/ 的音，类似 "Village"。不要重读第二个音节变成 "Age"。',
    codeSnippet: 'Image img;\nimg.load("texture.png");'
  },
  {
    id: 'ajax',
    word: 'AJAX',
    ipa: 'ˈeɪdʒæks',
    ipaUS: 'ˈeɪdʒæks',
    ipaUK: 'ˈeɪdʒæks',
    simplePhonetic: 'Ay-jacks',
    category: TermCategory.CONCEPT,
    description: '异步 JavaScript 和 XML。',
    commonError: 'A-Jax (阿贾克斯)',
    detailedExplanation: '虽然是足球队名阿贾克斯的拼写，但在技术圈读作 /eɪdʒæks/。A 发字母音 /ei/。',
    codeSnippet: '$.ajax({ url: "/api" });\n// Web request'
  },
  {
    id: 'malloc',
    word: 'malloc',
    ipa: 'ˈmælɒk',
    ipaUS: 'ˈmælɑːk',
    ipaUK: 'ˈmælɒk',
    simplePhonetic: 'Mal-lok',
    category: TermCategory.KEYWORD,
    description: 'Memory Allocation。',
    commonError: 'Ma-lo-k (马洛克)',
    detailedExplanation: 'Memory Allocation 的缩写。重音在第一个音节 Mal。第二个音节 loc 读作 lock。',
    codeSnippet: 'void* p = malloc(1024);\nfree(p);'
  }
];